name: Lint

on:
  push:
    branches: [main]
    paths:
      - ".github/actions/setup-python-with-uv/action.yml"
      - ".github/workflows/test.yml"
      - "**.py"
      - ".coveragerc"
      - ".env**"
      - ".python-version"
      - "tests"
      - "pyproject.toml"
      - "pytest.ini"
      - "uv.lock"
  pull_request:
    paths:
      - ".github/actions/setup-python-with-uv/action.yml"
      - ".github/workflows/lint.yml"
      - "**.py"
      - "**.sql"
      - ".python-version"
      - "pyproject.toml"
      - "ruff.toml"
      - "ty.toml"
      - "uv.lock"

jobs:
  ruff:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-with-uv

      - name: Lint by Ruff
        run: uv run nox -s lint -- --ruff

  ty:
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-with-uv

      - name: Lint by ty
        run: uv run nox -s lint -- --ty
